export enum NotificationType {
  // General
  INFO = "INFO",
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  ERROR = "ERROR",

  // Task
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_OVERDUE = "TASK_OVERDUE",
  TASK_COMMENTED = "TASK_COMMENTED",
  TASK_MENTIONED = "TASK_MENTIONED",

  // Workspace
  WORKSPACE_INVITED = "WORKSPACE_INVITED",
  WORKSPACE_MEMBER_JOINED = "WORKSPACE_MEMBER_JOINED",
  WORKSPACE_MEMBER_REMOVED = "WORKSPACE_MEMBER_REMOVED",

  // Project
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_ARCHIVED = "PROJECT_ARCHIVED",
  PROJECT_INVITED = "PROJECT_INVITED",

  // Automation
  AUTOMATION_EXECUTED = "AUTOMATION_EXECUTED",
  AUTOMATION_FAILED = "AUTOMATION_FAILED",

  // Attachment
  ATTACHMENT_UPLOADED = "ATTACHMENT_UPLOADED",

  // Comment
  COMMENT_REPLY = "COMMENT_REPLY",
}